export const merchandiseAdmin = {
    name: 'Name',
    description: 'Description',
    price: 'Price',
    imageUrl: 'Image Url',
    newName: 'New Name',
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    deleteProduct: 'Delete Product',
    productAdded: 'Product added',
    productUpdated: 'Product Updated',
    productDeleted: 'Product Deleted',
    edit: 'Edit',
    changesSaved: 'Changes saved',
    pmc: 'Product Management Centre',
    adminLogin: 'Admin Login',
    adminLogout: 'Admin Logout',
    tableError: 'There was an error loading the table. Please try again later.',
    submit: "Submit",
    close: "Close",
    delete: 'Delete',
    deleteMessage: 'Are you sure you want to delete ',
    cancel: 'Cancel',
    add: 'Add'
}