export const mixes = {
    mixes: "Mixes",
    mixesDescription: "Feel free to listen to my shit mixywixy's",
    dark2Link: "https://drive.google.com/file/d/12ApRvbeb02d0qVvO31S0YFEHDLFcuVIV/view?usp=drive_link",
    dark2: 'dark 2',
    dark3Link: 'https://drive.google.com/file/d/17YAAFuf8joqz3RqnjWvYPFWB694gABPk/view?usp=sharing',
    dark3: 'dark 3',
    skatty1Link: 'https://drive.google.com/file/d/1wjzrl5ZJ-PoeYoi5nO1WsvQpX7e5iIko/view?usp=sharing',
    skatty1: 'skatty1',
    dark4Link: 'https://drive.google.com/file/d/1QxsVeL5k-9s9OXUdwWSYe3BDiOSwIPmN/view?usp=sharing',
    dark4: 'dark4',
    hospitality2Link: 'https://drive.google.com/file/d/1Q_REzroYpm2e7evd1ySDbZcC-6tMEd6K/view?usp=sharing',
    hospitality2: 'hospitality 2',
    dark5Link: 'https://drive.google.com/file/d/1K5i7KCsqO_kugoGmlMkPDlQ1zcUaDHSp/view?usp=sharing',
    dark5: 'dark 5',
    dark6Link: 'https://drive.google.com/file/d/1abE5oJRKAgQFVa1TSFl-bVi8bj7eb0QV/view?usp=sharing',
    dark6: 'dark 6',
    dark7Link: 'https://drive.google.com/file/d/1E11UFx1_NJAyZAK0HLk0GszNcMciFywP/view?usp=sharing',
    dark7: 'dark 7 (screamarts/skylark)',
    dark8Link: 'https://drive.google.com/file/d/1G4PXbslaxBE3GWZJK-Jn9ZtWZNxTT3w5/view?usp=sharing',
    dark8: 'dark8',
    dark9Link: 'https://drive.google.com/file/d/1HHJTF1sdvZAgDt-oUUTiSicBII-HJy5u/view?usp=sharing',
    dark9: 'dark9',
    dark10Link: 'https://drive.google.com/file/d/1OOZBY60VDdv6j91-6qNK-SuBobkh3Pvn/view?usp=sharing',
    dark10: 'dark10',
    dark11Link: 'https://drive.google.com/file/d/1M5WrLF0ivS2j3U1n3c7BDNLhcS9WGldL/view?usp=sharing',
    dark11: 'dark11',
    dark13DnbLink: 'https://drive.google.com/file/d/1v_m6zUKETo1mdkmWGtJOWlA36dE6dgh6/view?usp=sharing',
    dark13Dnb: 'dark 13 [1985 dnb]'
}